columns:
- network_packet_size: float64
- protocol_type: int64
- login_attempts: int64
- session_duration: float64
- encryption_used: int64
- ip_reputation_score: float64
- failed_logins: int64
- browser_type: int64
- unusual_time_access: int64
- attack_detected: int64
numerical_columns:
- network_packet_size
- protocol_type
- login_attempts
- session_duration
- encryption_used
- ip_reputation_score
- failed_logins
- browser_type
- unusual_time_access
- attack_detected